site_name: Notatki z języków
theme:
  name: material
  palette:
    scheme: slate

repo_name: pktiuk/notatki_z_jezykow
repo_url: https://github.com/pktiuk/notatki_z_jezykow

markdown_extensions:
  - codehilite
  - admonition
