name: Deploy

on:
  push:
    branches:
      - "master"


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get install python3-setuptools
        pip3 install mkdocs mkdocs-material mdx_truly_sane_lists
        
    - name: Deploy MkDocs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
