name: Deploy

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install deps
      run: pip3 install mkdocs mkdocs-material
        
    - name: Deploy MkDocs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
